### ISSUE TITLE
Equality Design

### ISSUE THREAD

**Issue by aljce** [andrewthad/natural-arithmetic#1]
Why didn’t you use `(:~:)` for equality on the naturals?

**Comment by aljce** [comment]
Oh was it to avoid unsafeCoerce?

**Comment by andrewthad** [comment]
That’s half of it. The other half is that when unlifted newtypes lands in GHC 8.10, I’m going to change the implementation so that all of the proof types are of kind `TYPE ‘VoidRep` so that they can be embedded in other data types at no cost.
